name: teachers
version: '3.8'

services:
  # MongoDB сервис
  mongodb_teachers:
    image: mongo:latest
    container_name: mongodb_teachers
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: teachers
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local